# Generated by Django 5.2.6 on 2025-09-15 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("target_region", models.CharField(max_length=200)),
                ("target_audience", models.TextField()),
                ("campaign_message", models.TextField()),
                (
                    "products",
                    models.JSONField(
                        help_text="Array of products: [{'name': 'Product A', 'type': 'Energy Drink'}]"
                    ),
                ),
                (
                    "translation_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Translation settings and overrides",
                    ),
                ),
                (
                    "reference_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional reference image that will be normalized to 1024x1024 and used as the first generated asset",
                        null=True,
                        upload_to="reference_images/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 639-1 language code (e.g., 'en', 'es', 'ja')",
                        max_length=5,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Language name in English (e.g., 'English', 'Spanish', 'Japanese')",
                        max_length=50,
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        blank=True,
                        help_text="Language name in native script (e.g., '日本語')",
                        max_length=50,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("ltr", "Left-to-Right"),
                            ("rtl", "Right-to-Left"),
                            ("ttb", "Top-to-Bottom"),
                        ],
                        default="ltr",
                        help_text="Text direction for this language",
                        max_length=10,
                    ),
                ),
                (
                    "script",
                    models.CharField(
                        choices=[
                            ("latin", "Latin"),
                            ("hiragana", "Hiragana"),
                            ("katakana", "Katakana"),
                            ("han", "Han (Chinese/Japanese)"),
                            ("hangul", "Hangul"),
                            ("arabic", "Arabic"),
                            ("hebrew", "Hebrew"),
                            ("cyrillic", "Cyrillic"),
                        ],
                        default="latin",
                        help_text="Primary script type for this language",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this language is available for campaigns",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GenerationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_index",
                    models.IntegerField(
                        help_text="Sequential run number for this brief"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("assets_generated", models.IntegerField(default=0)),
                ("total_generation_time", models.FloatField(default=0.0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_runs",
                        to="campaign_generator.brief",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "unique_together": {("brief", "run_index")},
            },
        ),
        migrations.CreateModel(
            name="GenerationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("assets_generated", models.IntegerField(default=0)),
                ("total_generation_time", models.FloatField(default=0.0)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_sessions",
                        to="campaign_generator.brief",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DemoBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("target_region", models.CharField(max_length=200)),
                ("target_audience", models.TextField()),
                ("campaign_message", models.TextField()),
                (
                    "products",
                    models.JSONField(
                        help_text="Array of products: [{'name': 'Product A', 'type': 'Energy Drink'}]"
                    ),
                ),
                (
                    "translation_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Translation settings and overrides",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this demo brief for selection UI",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this demo brief appears in the selection UI",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_language",
                    models.ForeignKey(
                        default=1,
                        help_text="Primary language for this campaign",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_demo_briefs",
                        to="campaign_generator.language",
                    ),
                ),
                (
                    "supported_languages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional languages to generate assets for",
                        related_name="supported_demo_briefs",
                        to="campaign_generator.language",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="brief",
            name="primary_language",
            field=models.ForeignKey(
                default=1,
                help_text="Primary language for this campaign",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_briefs",
                to="campaign_generator.language",
            ),
        ),
        migrations.AddField(
            model_name="brief",
            name="supported_languages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional languages to generate assets for",
                related_name="supported_briefs",
                to="campaign_generator.language",
            ),
        ),
        migrations.CreateModel(
            name="GeneratedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                (
                    "aspect_ratio",
                    models.CharField(
                        choices=[
                            ("1:1", "Square (1:1)"),
                            ("9:16", "Vertical Story (9:16)"),
                            ("16:9", "Horizontal Video (16:9)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "translation_status",
                    models.CharField(
                        choices=[
                            ("original", "Original"),
                            ("translated", "Translated"),
                            ("failed", "Translation Failed"),
                            ("pending", "Translation Pending"),
                        ],
                        default="original",
                        help_text="Translation status of this asset",
                        max_length=20,
                    ),
                ),
                (
                    "translated_campaign_message",
                    models.TextField(
                        blank=True,
                        help_text="Translated campaign message for this language",
                    ),
                ),
                ("ai_prompt", models.TextField()),
                ("generation_time_seconds", models.FloatField(blank=True, null=True)),
                ("image_file", models.ImageField(blank=True, upload_to="generated/")),
                (
                    "organized_file_path",
                    models.CharField(
                        help_text="Path in organized output structure", max_length=500
                    ),
                ),
                (
                    "is_reference_image",
                    models.BooleanField(
                        default=False,
                        help_text="True if this asset was created from an uploaded reference image",
                    ),
                ),
                (
                    "reference_image_note",
                    models.CharField(
                        blank=True,
                        help_text="Note about the reference image processing (e.g., 'Normalized from uploaded reference')",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_assets",
                        to="campaign_generator.brief",
                    ),
                ),
                (
                    "original_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to original asset if this is a translation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaign_generator.generatedasset",
                    ),
                ),
                (
                    "generation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="campaign_generator.generationrun",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        default=1,
                        help_text="Language for this asset",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="campaign_generator.language",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["language", "aspect_ratio"],
                        name="campaign_ge_languag_fa3702_idx",
                    ),
                    models.Index(
                        fields=["brief", "language"],
                        name="campaign_ge_brief_i_14c730_idx",
                    ),
                    models.Index(
                        fields=["translation_status"],
                        name="campaign_ge_transla_e31adc_idx",
                    ),
                ],
                "unique_together": {
                    ("generation_run", "product_name", "aspect_ratio", "language")
                },
            },
        ),
    ]
