# Generated by Django 5.2.6 on 2025-09-14 18:54

import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brief",
            name="reference_image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                help_text="Optional reference image that will be normalized to 1000x1000 and used as the first generated asset",
                null=True,
                upload_to="reference_images/",
            ),
        ),
        migrations.AddField(
            model_name="generatedasset",
            name="is_reference_image",
            field=models.BooleanField(
                default=False,
                help_text="True if this asset was created from an uploaded reference image",
            ),
        ),
        migrations.AddField(
            model_name="generatedasset",
            name="reference_image_note",
            field=models.CharField(
                blank=True,
                help_text="Note about the reference image processing (e.g., 'Normalized from uploaded reference')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="brief",
            name="primary_language",
            field=models.ForeignKey(
                default=1,
                help_text="Primary language for this campaign",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_briefs",
                to="campaign_generator.language",
            ),
        ),
        migrations.AlterField(
            model_name="generatedasset",
            name="language",
            field=models.ForeignKey(
                default=1,
                help_text="Language for this asset",
                on_delete=django.db.models.deletion.PROTECT,
                to="campaign_generator.language",
            ),
        ),
    ]
