# Generated by Django 5.2.6 on 2025-09-14 21:07

import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign_generator", "0002_brief_reference_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brief",
            name="reference_image",
            field=versatileimagefield.fields.VersatileImageField(
                blank=True,
                help_text="Optional reference image that will be normalized to 1024x1024 and used as the first generated asset",
                null=True,
                upload_to="reference_images/",
            ),
        ),
        migrations.CreateModel(
            name="DemoBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("target_region", models.CharField(max_length=200)),
                ("target_audience", models.TextField()),
                ("campaign_message", models.TextField()),
                (
                    "products",
                    models.JSONField(
                        help_text="Array of products: [{'name': 'Product A', 'type': 'Energy Drink'}]"
                    ),
                ),
                (
                    "translation_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Translation settings and overrides",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this demo brief for selection UI",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this demo brief appears in the selection UI",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_language",
                    models.ForeignKey(
                        default=1,
                        help_text="Primary language for this campaign",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_demo_briefs",
                        to="campaign_generator.language",
                    ),
                ),
                (
                    "supported_languages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Additional languages to generate assets for",
                        related_name="supported_demo_briefs",
                        to="campaign_generator.language",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
