# Generated by Django 5.2.6 on 2025-09-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign_generator", "0003_alter_brief_reference_image_demobrief"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenerationSession",
        ),
    ]
